### ISSUE TITLE
Having trouble getting this to work, 

### ISSUE THREAD

**Issue by BrambleWolf** [emredurak01/tome-auto_fight#1]
I installed, enabled, set a skill, press x and....nothing.

Any idea?

**Comment by emredurak01** [comment]
I just tested and it works fine. Can you check everything for me?
In menu > keybindings, do you have "Auto Fight Button" assigned to X below the actions tab?
Do you have another key assigned to X? Maybe another action overrides it.
Can you disable all other mods except this and try again? Maybe there is some conflict with some other mod.
What class are you playing? I haven't tested with all the classes. Currently playing Bulwark with no issues. If you don't get anything printed on the chat most likely there is an issue with your key binding. 
Also, you said you "unzipped" the file in the mod page but there is nothing to unzip. It downloads a .teaa file. Make sure you have the addon enabled in your save file.

**Comment by BrambleWolf** [comment]
Dude you rule for responding,


Ok so:

I don't have an entry for auto fight in my keybinds
I don't have any key assigned to 'x'
this is the only mod I have, and it's the only mod I want
I tried the most vanilla thing ever, a bulwark, but im open to changing classes 

Attached is my mod setup.
![image](https://github.com/emredurak01/tome-auto_fight/assets/85409633/22d7f489-7ff8-4cf4-a18c-c319f2fbf43c)

**Comment by BrambleWolf** [comment]
I tried downloading the files as a zip, from github, as well as downloading the teaa from the tome site that links to here, same thing

How do you enable a mod in a save?

**Comment by emredurak01** [comment]
![image](https://github.com/emredurak01/tome-auto_fight/assets/69764150/e6c8e336-038b-43dd-b51b-97dfb6ae528b)

In the load game screen does your save file look like this? Required files should have auto_fight. Also if you are playing on Steam can you try deleting the addon manually and installing the addon from the workshop?

**Comment by BrambleWolf** [comment]
You beautiful bastard!! it works!!!!

**Comment by BrambleWolf** [comment]
I uninstalled the teaa file, and redownloaded the one from the tome4 site, made a new character and bam!

**Comment by BrambleWolf** [comment]
This is the greatest fuckign thing ever, I don't understand why everyone doesnt have this, this is essential to skipping the tedium of clicking my number keys to kill the 102nd fucking rat.

**Comment by BrambleWolf** [comment]
Do you have a donation link? this is worth 5$ to me

**Comment by emredurak01** [comment]
Yeah, I loved this feature from DCSS, it removes the tediousness of the early game. There is another mod similar to this but it was buggy as hell, so I decided to remake it. Glad you like it, no need for a donation, just have fun :) Closing the issue, if you encounter any bugs please open another one.
